local:

  redis:
    host: redis.host
    port: 6379

  mysql:
    url: jdbc:mysql://mysql:3306/demo?useTimezone=true&serverTimezone=GMT&autoReconnect=true&useSSL=false
    user: root
    pass: mysql
